### ISSUE TITLE
Fulp and Old FTL13 are wrong

### ISSUE THREAD

**Issue by ike709** [spacestation13/SS13-Codebases#1]
Fulp is an AGPL TG fork, Old FTL13 is a yogs fork.

**Comment by ghost** [comment]
fulp was first a yog fork but not anymore. FTL13 was originally a yog fork for like, half a year? then became agpl tg. We were never not agpl.

**Comment by ZeWaka** [comment]
> fulp was first a yog fork but not anymore. FTL13 was originally a yog fork for like, half a year? then became agpl tg. We were never not agpl.

Fixed in da12e4545856e41cc0545b388bf755845cb9ad56

**Comment by ghost** [comment]
ty
