### ISSUE TITLE
Suggestion: SS13 GitHub List

### ISSUE THREAD

**Issue by cosmiccoincidence** [spacestation13/SS13-Codebases#23]
## Summary 

A list of SS13 codebases with links to their GitHub repos.

I went looking for one and initially didn't find one, but was looking around your repo when I found your archived repo here: https://github.com/spacestation13/Space-Station-13 though it's a very short but detailed list. I'm curious to as why it's archived, and suggest you revive it or maybe add the list to this repo.

**Comment by ZeWaka** [comment]
Feel free to revive that project if you want, just open PRs to it.
